### ISSUE TITLE
Repository is incompatible with WoWUp

### ISSUE THREAD

**Issue by KevinTyrrell** [blacha/uGain#3]
Installing uGain for TBC using WoWUp by inputting the URL of this repository yields the following error:

![image](https://user-images.githubusercontent.com/12791400/170535266-e2ac0208-7cec-4af0-aaa0-a8a0ef3084d7.png)

The URL used for installing for the above image was: https://github.com/blacha/uGain

In order for WoWUp to recognize this repository, you must create a [Release](https://github.com/blacha/uGain/releases) that includes a `.zip` file whose file name ends with `-bcc`. For example the zip file may be called `uGainv1.0.0-bcc.zip`

Given the popularity of WoWUp and the lack of Curseforge as an option, it is highly recommended you make this repository compatible with WoWUp in order to allow ease-of-use when installing.

**Comment by blacha** [comment]
Ahh looks like this is just done the packaging github action, bigwigs/Packager it is just missing a token to actually publish the files, Ill add a token and make a new release.

**Comment by blacha** [comment]
A release has been published https://github.com/blacha/uGain/releases/tag/v0.2.1, 

I don't have a active wow subscription so I cant test that it actually works though

**Comment by KevinTyrrell** [comment]
That did the trick. It installed and works correctly. Closing the issue.

> the packaging github action, bigwigs/Packager it is just missing a token to actually publish the files

Can you explain what you mean by this? In my applications I have to manually create a zip file, go to the releases section, click upload, manually add description and title, etc. I've heard there was a better way but have never experimented with it before. I know basics abou 'tagging' which can automatically create releases but that's all. Curious how you did it.

> I don't have a active wow subscription so I cant test that it actually works though

Phase 5 is very fun and challenging -- you should reconsider!

**Comment by blacha** [comment]
> Can you explain what you mean by this? 

I use a github action made by bigwigs, https://github.com/BigWigsMods/packager

this github action runs on every push to master, using github actions and bundles everything into a zip. https://github.com/blacha/uGain/blob/master/.github/workflows/release.yml#L4

when I push a tag, it creates a proper release from all the commit messages since the last tag and then uploads it

```bash
git tag v0.2.1
git push --tags
```

I have given it access to github and to curse by supplying api tokens 

https://github.com/blacha/uGain/blob/master/.github/workflows/release.yml#L35

**Comment by KevinTyrrell** [comment]
That's amazing. I feel like a caveman doing it manually with my addon. I honestly click 'hide' whenever I see a new GitHub feature but I should really start experimenting. Thanks for the help.
